CREATE SCHEMA IF NOT EXISTS spotifive;

USE spotifive;

CREATE SEQUENCE IF NOT EXISTS SONG_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS PLAY_LIST_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS PLAY_LIST_SONG_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS USERS_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS MODULES_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS PRIVILEGES_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS MODULE_PRIVILEGES_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS USER_MODULE_PRIVILEGE_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS SONG (
    id BIGINT NOT NULL DEFAULT NEXTVAL('SONG_SEQ') PRIMARY KEY,
    title VARCHAR(255),
    artist VARCHAR(255),
    album VARCHAR(255),
    annio INTEGER,
    genre VARCHAR(100)
    );

CREATE TABLE IF NOT EXISTS PLAY_LIST (
    id BIGINT NOT NULL DEFAULT NEXTVAL('PLAY_LIST_SEQ') PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(500)
    );

CREATE TABLE IF NOT EXISTS PLAY_LIST_SONG (
    id BIGINT NOT NULL DEFAULT NEXTVAL('PLAY_LIST_SONG_SEQ') PRIMARY KEY,
    play_list_id BIGINT,
    song_id BIGINT,
    FOREIGN KEY (play_list_id) REFERENCES PLAY_LIST(id),
    FOREIGN KEY (song_id) REFERENCES SONG(id)
    );

CREATE TABLE IF NOT EXISTS USERS (
    id BIGINT NOT NULL DEFAULT NEXTVAL('USERS_SEQ') PRIMARY KEY,
    username VARCHAR(255),
    password VARCHAR(255),
    email VARCHAR(255),
    refresh_token VARCHAR(500),
    refresh_token_expiration TIMESTAMP,
    failed_attempts BIGINT DEFAULT 0,
    status BIGINT DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS MODULES (
    id BIGINT NOT NULL DEFAULT NEXTVAL('MODULES_SEQ') PRIMARY KEY,
    name VARCHAR(255),
    key VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS PRIVILEGE (
    id BIGINT NOT NULL DEFAULT NEXTVAL('PRIVILEGES_SEQ') PRIMARY KEY,
    name VARCHAR(255),
    key VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS MODULE_PRIVILEGES (
    id BIGINT NOT NULL DEFAULT NEXTVAL('MODULE_PRIVILEGES_SEQ') PRIMARY KEY,
    module_id BIGINT,
    privilege_id BIGINT,
    key VARCHAR(255),
    FOREIGN KEY (module_id) REFERENCES MODULES(id),
    FOREIGN KEY (privilege_id) REFERENCES PRIVILEGE(id)
    );

CREATE TABLE IF NOT EXISTS USER_MODULE_PRIVILEGE (
    id BIGINT NOT NULL DEFAULT NEXTVAL('USER_MODULE_PRIVILEGE_SEQ') PRIMARY KEY,
    user_id BIGINT,
    module_privilege_id BIGINT,
    FOREIGN KEY (user_id) REFERENCES USERS(id),
    FOREIGN KEY (module_privilege_id) REFERENCES MODULE_PRIVILEGES(id)
    );


