CREATE SCHEMA IF NOT EXISTS spotifive;

USE spotifive;

CREATE SEQUENCE IF NOT EXISTS SONG_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS PLAY_LIST_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS PLAY_LIST_SONG_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS SONG (
    id BIGINT NOT NULL DEFAULT NEXTVAL('SONG_SEQ') PRIMARY KEY,
    title VARCHAR(255),
    artist VARCHAR(255),
    album VARCHAR(255),
    annio INTEGER,
    genre VARCHAR(100)
    );

CREATE TABLE IF NOT EXISTS PLAY_LIST (
    id BIGINT NOT NULL DEFAULT NEXTVAL('PLAY_LIST_SEQ') PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(500)
    );

CREATE TABLE IF NOT EXISTS PLAY_LIST_SONG (
    id BIGINT NOT NULL DEFAULT NEXTVAL('PLAY_LIST_SONG_SEQ') PRIMARY KEY,
    play_list_id BIGINT,
    song_id BIGINT,
    FOREIGN KEY (play_list_id) REFERENCES PLAY_LIST(id),
    FOREIGN KEY (song_id) REFERENCES SONG(id)
    );


