CREATE SCHEMA IF NOT EXISTS spotifive;

USE spotifive;

CREATE SEQUENCE IF NOT EXISTS SONG_SEQ
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS SONG (
    id BIGINT NOT NULL DEFAULT NEXTVAL('SONG_SEQ') PRIMARY KEY,
    title VARCHAR(255),
    artist VARCHAR(255),
    album VARCHAR(255),
    annio INTEGER,
    genre VARCHAR(100)
    );


